name: Deploy NestJS Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build NestJS application
      run: npm run build

    - name: Archive build files
      run: zip -r build.zip dist node_modules package.json

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_SECRET_KEY }}
        source: "build.zip"
        target: "~/nestjs-app/"

    - name: SSH and restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_SECRET_KEY }}
        script: |
          cd ~/nestjs-app/
          unzip -o build.zip
          npm install --production
          pm2 restart all || pm2 start dist/main.js --name nestjs-app
